# Pre-commit hooks for code quality - never blocks!
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: format-and-stage
        name: Format code and stage changes (never blocks)
        entry: ./.pre-commit-wrapper.sh
        language: system
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
